package lottery;

import java.io.File;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 李子琪
 */
public class Display extends javax.swing.JFrame {

    /**
     * Creates new form Display
     */
    public Display() {
        initComponents();//系统生成代码
        this.setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        button.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTable = new javax.swing.JTable();
        panel = new javax.swing.JPanel();
        numText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        startText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        endText = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        eventText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        radiobutton1 = new javax.swing.JRadioButton();
        radiobutton2 = new javax.swing.JRadioButton();
        radiobutton3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        fileButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        button.setText("开始抽奖");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        listTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "抽奖话题", "中奖人员", "对应奖项"
            }
        ));
        listTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listTable);

        numText.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        numText.setText("请输入整数");

        jLabel1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel1.setText("抽奖人数：");

        jLabel2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel2.setText("抽奖事件");

        jLabel3.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel3.setText("开始时间");

        startText.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        startText.setText("2022-1-1 0:0:0");

        jLabel4.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel4.setText("开始时间");

        endText.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        endText.setText("2022-12-1 0:0:0");
        endText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTextActionPerformed(evt);
            }
        });

        jScrollPane4.setHorizontalScrollBar(null);

        eventText.setColumns(20);
        eventText.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        eventText.setLineWrap(true);
        eventText.setRows(5);
        eventText.setText("#我要红包#");
        jScrollPane4.setViewportView(eventText);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numText, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(startText)
                    .addComponent(endText)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jTable1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"一等奖"},
                {"二等奖"},
                {"三等奖"}
            },
            new String [] {
                "奖品列表"
            }
        ));
        jTable1.setEnabled(false);
        jTable1.setRowHeight(20);
        jScrollPane2.setViewportView(jTable1);

        buttonGroup1.add(radiobutton1);
        radiobutton1.setSelected(true);
        radiobutton1.setText("不过滤");

        buttonGroup1.add(radiobutton2);
        radiobutton2.setText("普通过滤");

        buttonGroup1.add(radiobutton3);
        radiobutton3.setText("深度过滤");

        jLabel5.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel5.setText("过滤方式");

        fileButton.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        fileButton.setText("打开文件");
        fileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(radiobutton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radiobutton2)
                                            .addComponent(radiobutton1)
                                            .addComponent(jLabel5))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(fileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 767, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(fileButton)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radiobutton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radiobutton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radiobutton3)
                                .addGap(63, 63, 63)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        String startString=startText.getText();
        String endString=endText.getText();
        int num;
        List<String> list=null;
        int filterType=1;
       
        String eventString =eventText.getText();
        
        try//检测数量格式
        {
            num=Integer.parseInt(numText.getText());
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "数量不是整数", "数量不是整数", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(radiobutton1.isSelected()) filterType=1;//过滤模式
        else if(radiobutton2.isSelected()) filterType=2;
        else if(radiobutton3.isSelected()) filterType=3;
        
        if(num>qq.getAllUserId().size())
        {
            JOptionPane.showMessageDialog(null, "人数大于所有人", "人数大于所有人", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(filterType==1)list=Way.create().none(qq.getAllUserId(), num);
        else if(filterType==2)list=Way.create().common(qq.getDrawList(stringToDate(startString), stringToDate(endString), eventString),qq, num);
        else if(filterType==3)list=Way.create().deep(qq.getDrawList(stringToDate(startString), stringToDate(endString), eventString),qq, num);
        
        DefaultTableModel model=(DefaultTableModel)listTable.getModel();
        int cnt=model.getRowCount();
        if(cnt>0)
        {
            for(int i=0;i<cnt;i++) model.removeRow(0);//清空上一次的名单
        }
        if(list!=null)
        {
            for(int i=0;i<list.size();i++)//更新列表
            {
                if(i<2)
                {
                    model.addRow(new Object[]{
                        eventText.getText(),list.get(i),"一等奖"
                    });
                }
                else if(i<5)
                {
                    model.addRow(new Object[]{
                        eventText.getText(),list.get(i),"二等奖"
                    });
                }
                else
                {
                    model.addRow(new Object[]{
                        eventText.getText(),list.get(i),"三等奖"
                    });
                }
            }
        }
    }//GEN-LAST:event_buttonActionPerformed

    private void endTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endTextActionPerformed
    
    
    private void fileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButtonActionPerformed
        JFileChooser jfc=new JFileChooser();  
        jfc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES );  
        jfc.showDialog(new JLabel(), "选择");  
        File file=jfc.getSelectedFile(); 
        qq=new ProcessQQLog(file.getAbsolutePath());
        button.setEnabled(true);
    }//GEN-LAST:event_fileButtonActionPerformed

    private Date stringToDate(String s)//字符串转化为日期
    {
        //2015-05-15 12:54:45
        int index1 = 0;
        while(s.charAt(index1) != '-')
            index1++;
        int index2 = index1+1;
        while(s.charAt(index2) != '-')
            index2++;
        int y = Integer.parseInt(s.substring(0, index1));
        int m = Integer.parseInt(s.substring(index1+1, index2));
        int index3 = index2 + 1;
        while(s.charAt(index3) != ' ')
            index3++;
        int d = Integer.parseInt(s.substring(index2+1, index3));
        int index4 = index3+1;
        while(s.charAt(index4) != ':')
            index4++;
        int h = Integer.parseInt(s.substring(index3+1, index4));
        int index5 = index4 + 1;
        while(s.charAt(index5) != ':')
            index5++;
        int min = Integer.parseInt(s.substring(index4+1, index5));
        int se = Integer.parseInt(s.substring(index5+1, s.length()));
        return new Date(y,m,d,h,min,se);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField endText;
    private javax.swing.JTextArea eventText;
    private javax.swing.JButton fileButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable listTable;
    private javax.swing.JTextField numText;
    private javax.swing.JPanel panel;
    private javax.swing.JRadioButton radiobutton1;
    private javax.swing.JRadioButton radiobutton2;
    private javax.swing.JRadioButton radiobutton3;
    private javax.swing.JTextField startText;
    // End of variables declaration//GEN-END:variables
    private ProcessQQLog qq ;
}

